// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppForm: typeof import('./resources/js/components/forms/AppForm.vue')['default']
    AvailableVariablesExpander: typeof import('./resources/js/components/AvailableVariablesExpander.vue')['default']
    DownloadLinkInput: typeof import('./resources/js/components/DownloadLinkInput.vue')['default']
  }
}
