version: '3'
services:
    php:
        image: 'serversideup/php:8.2-fpm-nginx'
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
        networks:
            - supdater
        environment:
            AUTORUN_LARAVEL_MIGRATION: true
            # SSL_MODE: "off"
            # AUTORUN_LARAVEL_STORAGE_LINK: false
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        networks:
            - supdater
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - supdater
networks:
    supdater:
        driver: bridge
